version: 0.2
phases:
  build:
    commands:
      - sam build
      - sam deploy --stack-name tagesdashboard-sam --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND --resolve-s3 --no-confirm-changeset --no-fail-on-empty-changeset
