---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Amazon CodePipeline - Project for Tagesdashboard SAM IaC'

Parameters:
  CodeBuildTdbSamStackBuildProjectNamePrefix:
    Description:  Name of the CodeBuild project that builds the SAM deployment for Tagesdashboard
    Type: String
    Default: TdbSamCodeBuildCf
  CodePipelineTdbSamStackPipelineNamePrefix:
    Description:  Name of the CodePipeline pipeline that deploys the SAM backend app for Tagesdashboard
    Type: String
    Default: TdbSamCodePipelineCf
  CfPipelineServiceRoleSuffix:
    Type: String
    Description: Suffix for previously generated CodePipeline service role
    Default: EksCfPipeline
  TdbGitHubBranch:
    Description:  Branch name to use for CodeBuild
    Type: String
    Default: develop
  TdbArtifactsBucket:
    Description:  The bucket name of the TDB artifacts
    Type: String
    Default: tdb-sam-artifacts

Resources:
  TdbSamCodeBuildServicePolicy:
      Type: AWS::IAM::Policy
      Properties:
        PolicyName: TdbSamCodeBuildSvcPolicy
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - 's3:ListBucket'
              Resource: !Sub 'arn:aws:s3:::${TdbArtifactsBucket}'
            - Effect: Allow
              Action:
                - 's3:GetObject'
                - 's3:GetObjectVersion'
                - 's3:PutObject'
                - 's3:DeleteObject'
                - 's3:GetBucketAcl'
                - 's3:GetBucketLocation'
                - 's3:ListBucket'
              Resource: !Sub 'arn:aws:s3:::${TdbArtifactsBucket}/*'
            - Effect: Allow
              Action:
                - 'logs:CreateLogGroup'
                - 'logs:CreateLogStream'
                - 'logs:PutLogEvents'
              Resource:
                - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild
                - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*
        Roles:
          - !Ref SamCodePipelineServiceRole
  SamCodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'TdbSamCodePipelineSvcRole-${AWS::StackName}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - !Sub 'arn:aws:iam::${AWS::AccountId}:policy/service-role/AWSCodePipelineServiceRole-${AWS::Region}-${CfPipelineServiceRoleSuffix}'
  TdbSamCodeBuildProject:
    Type:  AWS::CodeBuild::Project
    Properties:
      Name: !Sub '${CodeBuildTdbSamStackBuildProjectNamePrefix}-${AWS::StackName}'
      ServiceRole: !GetAtt SamCodePipelineServiceRole.Arn
      Source:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_LAMBDA_CONTAINER
        ComputeType: BUILD_LAMBDA_1GB
        Image: aws/codebuild/amazonlinux-x86_64-lambda-standard:python3.11
      Artifacts:
        Type: CODEPIPELINE
  TbdSamCodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub '${CodePipelineTdbSamStackPipelineNamePrefix}-${AWS::StackName}'
      RoleArn: !GetAtt SamCodePipelineServiceRole.Arn
      PipelineType: V2
      ExecutionMode: QUEUED
      ArtifactStore:
        Type: S3
        Location: !Ref TdbArtifactsBucket
      Triggers:
        - ProviderType: CodeStarSourceConnection
          GitConfiguration:
            SourceActionName: SourceAction
            Push:
              - Branches:
                  Includes:
                    - develop
      Stages:
       - Name: SourceStage
         Actions:
           - Name: SourceAction
             ActionTypeId:
               Category: Source
               Owner: AWS
               Provider: CodeStarSourceConnection
               Version: "1"
             OutputArtifacts:
               - Name: SourceOutput
             Configuration:
               ConnectionArn: !Sub "arn:aws:codestar-connections:${AWS::Region}:${AWS::AccountId}:connection/{{resolve:ssm:GitHubConnectionId}}"
               FullRepositoryId: "{{resolve:ssm:GitHubRepositoryOwner:1}}/{{resolve:ssm:/Tagesdashboard/GitHubRepositoryName:1}}"
               BranchName: !Ref TdbGitHubBranch
             RunOrder: 1
       - Name: BuildStage
         Actions:
          - Name: BuildAction
            InputArtifacts:
              - Name: SourceOutput
            ActionTypeId:
              Category: Build
              Owner: AWS
              Provider: CodeBuild
              Version: "1"
            OutputArtifacts:
              - Name: SAMBuildArtifact
            Configuration:
              ProjectName: !Ref TdbSamCodeBuildProject
